### ISSUE TITLE
Question about values returned by time() function?  Seem to be 20 years late?

### ISSUE THREAD

**Issue by dachshund-digital** [micropython/micropython-infineon#5]
Typical result (for recent date) on an ESP8266 would be 605078638 using the ntptime module in MicroPython.  Which obviously converts to a human readable date/time format, such as Sun, 05 Mar 1989 05:23:58 +0000 but clearly the month and day are correct but the year is off by 20 years?  Should be closer to something like 1551764000, no?  Packet is sent to NTP source and received as expected just not the result expected.

**Comment by dpgeorge** [comment]
MicroPython uses an Epoch of 2000/1/1 so that integers don't overflow 30 bits of precision (and floats are not always available).  In ntptime.py there is a variable NTP_DELTA that encodes this difference to the usual unix Epoch.

BTW: bugs should usually be opened against the main repository https://github.com/micropython/micropython

**Comment by dachshund-digital** [comment]
Ah, thanks for the reply.  Yeah, was not sure it was a bug, but just a difference with how ESP8266 implemented time. if you will.  I guess I could tweak the delta to get epoch time stamp aligned with what other systems do, seems to make more sense to handle it on the back end in database to align values.
